googleapis/release-please-action

dist/index.js, package-lock.json, package.json
I was pleasantly surprised when I've discovered that as of few hours ago, merge commits are now supported in release-please - big thanks @bcoe!
All I did here was I've ran `npm update` followed by `npm build` - I hope that's what I was supposed to do but if not, I'm happy to do it some other way.
I marked that as a fix, but I'm not sure whether incorporating upstream fixes should itself be a fix.
=> fix(deps): depend on release-please ^5.2.1 to support merge commits 

README.md
Updated version because `1.0.1` doesn't support some of the types below. Shouldn't have to get updated every time release-please is bumped, but should be somewhat relevant.
Also made the release type somewhat less confusing (IMO) for people starting out.
=> docs: bump version, change release format

README.md
Updates formatting and includes `outputs` table for reference. Based off #43.
=> docs: include `input` and `output`

README.md, dist/index.js, index.js, package-lock.json, package.json
Refs: https://github.com/googleapis/release-please/pull/501
=> feat: adds support for releases from alternate paths

README.md, action.yml, dist/index.js, index.js
Introduces the `command` option, which allows `github-release` and `release-pr` to be run separately.
=> feat: allow github-release/release-pr to be run separately

.github/workflows/release-please.yaml
- Instead of commits to main, open a PR with dist from a fork
- Generate diff of commits in dist (if able to find previous bot commit) and add to body of PR
- Use `google-github-actions-bot` for both build PR and release PR
=> chore: PR workflow for building dist

README.md, action.yml, index.js, package-lock.json, package.json, test/release-please.js
Opening a release PR now outputs a release #. Creating a GitHub release outputs SemVer major/minor/patch values
=> feat: add additional outputs

index.js
This variables are now used when multiple packages are being released from the same repository.
=> feat: pass monorepoTags and packageName when creating GitHub release

README.md
Python release type should refer to https://github.com/googleapis/python-storage
=> docs: address typo in README

package-lock.json, package.json
Ruby now uses `/` as a separator for version tags in monorepos, the same as go.
=> fix(release-please): patch branch detection logic

package-lock.json, package.json
Our gapic repository does not include any commits in a release for a submodule, if they're not prefixed with the appropriate commit [type](https://www.conventionalcommits.org/en/v1.0.0/#summary).
=> fix(go): filter additional PRs from gapic repo

action.yml, index.js
Allow `changelogPath` to be configured.
See: https://github.com/googleapis/google-cloud-go/pull/3441
=> feat: allow changelogPath to be specified

package-lock.json, package.json
The alternate tag separator was not properly being looked up for go.
=> fix(release-please): map go to alternate tag separator

index.js
We need to pass the release-type to the class that tags.
=> fix(go): pass release-type

README.md, action.yml, index.js, test/release-please.js
Fixes https://github.com/google-github-actions/release-please-action/issues/201
=> feat(release-please): add default branch input option

index.js, test/release-please.js
That Pr introduces the same defaultBranch support from PRs to gh release creation.
=> feat(release-please): add default branch input option for github release

index.js, package-lock.json, package.json, test/release-please.js
fixes #209 
* Updates to latest release please.
* Updates other packages.
=> feat(release-please): use latest release please version

index.js, test/release-please.js
**[URGENT]** - @v2 is currently broken.
This PR fixes the wrong call to createRelease now named as run.
Tests are also updated.
@bcoe This uses `.run`. Really sorry about that.
Can't believe I missed that. Paid too much attention to the class change but didn't see `.run` was also a breaking change. Mostly because the project uses Javascript and didn't "warn" me at all.
I also did some naming cleaning to make it easier on expect understanding.
=> fix(release-please): update github-release call to new function

README.md, index.js, test/release-please.js
Adds `manifest-pr` command for running PR creation step in isolation.
Refs: https://github.com/googleapis/google-api-nodejs-client/pull/2557
CC: @joeldodge79
=> feat(manifest): add manifest-pr command

index.js, test/release-please.js
If the special "." syntax is used for a manifest releaser (which represents a release in the root folder of a library) it should set the same outputs as a non-manifest releaser.
=> fix(manifest): if "." is used it should have same outputs non-mono-repo release strategy

index.js, test/release-please.js
We were just implementing a release process on a vscode extension in our monorepo, and that has a separate release flow than anything else, so we'd only want the publish phase to run if a specific path was released.
This adds a `release_created` flag on each published package in a manifest release.
=> feat: add release_created per path in manifest PR

index.js, test/release-please.js
Output a list of paths that releases were created for, so that it can be used in GitHub action matrix.
=> feat: output list of paths released during manifest release

README.md, action.yml, index.js, package-lock.json, package.json, test/release-please.js
Pass `bump-patch-for-minor-pre-major` to release-please to allow bumping
patch versions instead of minors for feat changes. Disabled by default. Change is backwards compatible.
This functionality was broken in release-please until now: https://github.com/googleapis/release-please/issues/1049
I suppose the fix should be in the new release of release-please soon.
Signed-off-by: Ilya Lesikov <ilya@lesikov.com>
=> feat: add `bump-patch-for-minor-pre-major` option

README.md, index.js
Hi everyone,
I want to use this action on Github enterprise, but this action default use Github API URL.
If users use Github enterprise, they need to be changed Github API URL.
this PR that add Github API URL input for this feature.
I hope to help this project to be better, thanks.
=> feat(input): add github API URL configuration for input

index.js
Hi everyone,
this action's first step didn't use apiUrl input, 
if user change apiUrl input then this action always use `https://api.github.com` endpoint, so this PR fix this case.
I hope to help this project to be better, thanks.
=> fix(config): add apiUrl config on Github release command

README.md, action.yml, index.js, package.json
Hi everyone,
I want to use this action on Github enterprise, 
but I find root cause that use different GraphQL URL between Github and Github enterprise
I upgrade release-please package version from 12.5.0 to 12.6.0,
we can change GraphQL URL on this release 12.6.0,
so I add input on GitHub GraphQL URL configuration
I hope to help this project to be better, thanks.
=> feat(input): add github GraphQL URL configuration for input

README.md
Since #398 the input booleans no longer accept `Yes` or `No`, but only `true` or `false`.
Some defaults mentionned in the readme are using the old format (Example: "default: `No`"), which is now outdated and misleading.
This PR updates the readme to use only boolean notation (`true`/`false`) when describing defaults.
=> docs(readme): Update defaults format to use booleans (`true`/`false`)

README.md, action.yml, dist/index.js, index.js
resolve #343
Add the `extra-files` input option.
See: https://github.com/googleapis/release-please/blob/main/docs/customizing.md#updating-arbitrary-files
=> feat: add extra-files input

index.js, package-lock.json, package.json, test/release-please.js
Upgrade release-please dep, address issue with manifest configuration
maintaining state between tagging releases and creating release PRs.
=> fix(release-please): upgrade release-please dep

package-lock.json, package.json
release-please v13.4.8 fixes an issue where include-component-in-tag is ignored in manifests.  This updates the dependency so that this action can benefit from the fix, as well.
Without this, https://github.com/google/shaka-player can't deploy release-please-action.
=> fix(release-please): Fix include-component-in-tag ignored in manifest

README.md, package-lock.json, package.json
Updating release-please to get the new features available to the github action:
* **rust:** update Cargo.lock for single Rust crate ([#1374](https://github.com/googleapis/release-please/issues/1374)) ([e3571d3](https://github.com/googleapis/release-please/commit/e3571d32c44ae2bef8bac7dd8cdc3556a9d621c7))
* added java strategy ([#1333](https://github.com/googleapis/release-please/issues/1333)) ([25f9c85](https://github.com/googleapis/release-please/commit/25f9c85a8472208a83dfd5cc4014c84adc3c771f))
* Restore v12 changelog formatting for ruby-yoshi ([#1361](https://github.com/googleapis/release-please/issues/1361)) ([ff87c7d](https://github.com/googleapis/release-please/commit/ff87c7df00b652512641454ead34bb2cede2f67e))
* add dotnet-yoshi strategy …
=> feat(deps): update release-please to 13.10.0

.github/dependabot.yml
This should help us keep the action up to date with the underlying release-please library
=> chore: enable dependabot for updating release-please

action.yml, index.js
Fixes https://github.com/google-github-actions/release-please-action/issues/525
=> feat: add a `changelog-host` parameter to `action.yml`

index.js
The fixes the build issue where the release-PR labels are defaulting to `[]` when it should default to `undefined`. `getMultilineInput()` defaults to returning `[]` when the config entry is not set.
This is causing the dogfood run of this action to fail: https://github.com/google-github-actions/release-please-action/runs/7845000323?check_suite_focus=true
This bug was introduced in #474  but is unreleased.
`@actions/core` does not provide any guidance on how to test default inputs.
=> fix: default labels should be undefined

README.md
=> docs: add documentation about caveats of using `GITHUB_TOKEN`

CHANGELOG.md, package-lock.json, package.json
Reverts google-github-actions/release-please-action#568
This was a bad build because monorepo-tags input's default is actually conditional
=> Revert "chore: release main"

action.yml, index.js
`monorepo-tags` default is actually conditional based on the number of components in the repo
Test ran this branch and it opened https://github.com/google-github-actions/release-please-action/pull/575 which is correct (not https://github.com/google-github-actions/release-please-action/pull/568)
=> fix: stop providing default values in action.yml

action.yml
Similar to #532, Fix #508
This allowed GitHub Enterprise users to use this action without specifying `changelog-host` to GitHub Enterprise Server URL
(related: #525, #550)
=> feat: read changelog-host url from action context

action.yml
release-please v14 requires node14+. GitHub actions does not support node14, so we jump to node16.
=> feat: run action on node16

package-lock.json, package.json
Ref: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
=> fix: bump @actions/core to get newer set-output syntax

package-lock.json, package.json, test/release-please.js
- https://github.com/googleapis/release-please/issues/1767
- https://github.com/googleapis/release-please/pull/1770
- https://github.com/googleapis/release-please/releases/tag/v14.17.5
=> Update `release-please` to `14.17.5`

README.md
- fixes a typo in the action outputs in README.md
- the code [here](https://github.com/google-github-actions/release-please-action/blob/main/index.js#L214) shows that the output variable is actually called `releases_created` instead of `release_created`
=> docs: Fix typo in action outputs

index.js
=> fix: tag releases before opening new pull requests

README.md
List `sfdx` as a supported release type
`sfdx` release type is included since release please [v15.9.0](https://github.com/googleapis/release-please/releases/tag/v15.9.0), which is used in the github action since [v3.7.6](https://github.com/google-github-actions/release-please-action/releases/tag/v3.7.6).
=> docs: add `sfdx` supported release type

README.md
Hey, perhaps I'm missing something, but as far as I understand it's not correct to use `package-name: release-please-action` verbatim – the name of the actual package in question should be used instead. This is not how I read the example workflow the README suggests to copy, so I hope this is an improvement.
=> docs: Clarify `package-name` in example

package-lock.json, package.json
Reverts google-github-actions/release-please-action#845
The action can't build the single js file via ncc with the newest version of release-please
```
ncc: Version 0.38.1
ncc: Compiling file index.js into CJS
Error: Module parse failed: Unexpected token (26:23)
File was processed with these loaders:
* ./node_modules/@vercel/ncc/dist/ncc/loaders/empty-loader.js
* ./node_modules/@vercel/ncc/dist/ncc/loaders/relocate-loader.js
* ./node_modules/@vercel/ncc/dist/ncc/loaders/shebang-loader.js
You may need an additional loader to handle the result of these loaders.
|     npm_lifecycle_event: event,
|     npm_lifecycle_script: cmd,
>     __webpack_require__.ab + "node-gyp.js",
|   })
| 
at /home/chingor/code/release-please-action/node_modules/@vercel/ncc/dist/ncc/index.js.cache.js:38:1896272
at …
```
=> Revert "fix: bump release-please from 15.13.0 to 16.1.0"

README.md, src/index.ts, test/release-please.ts
Sending the PR from a fork is something administrative that may be configured separately from the config.
=> feat: re-add fork option

README.md, action.yml, src/index.ts
v3 had this option and must be configurable or at least set to `false` so that the default behavior is to create a plain `v1.2.3` tag (without the component name prefixed).
Found this while dogfooding our own usage of the action (in this repo).
=> fix: restore include-component-in-tag default (false)

action.yml
The default should be to create plain tags like `v1.2.3`
=> build: the include-component-in-tag should default to false

.github/workflows/release-please.yaml
release-please already adds the `autorelease:pending` label
It has been failing for quite awhile with:
```
SyntaxError: missing ) after argument list
at new AsyncFunction (<anonymous>)
at callAsyncFunction (/home/runner/work/_actions/actions/github-script/v3/dist/index.js:7514:16)
Error: Unhandled error: SyntaxError: missing ) after argument list
at main (/home/runner/work/_actions/actions/github-script/v3/dist/index.js:7541:26)
at Module.720 (/home/runner/work/_actions/actions/github-script/v3/dist/index.js:7525:1)
at __webpack_require__ (/home/runner/work/_actions/actions/github-script/v3/dist/index.js:24:31)
at startup (/home/runner/work/_actions/actions/github-script/v3/dist/index.js:43:[19](https://github.com/google-github-actions/release-please-action/actions/runs/7064411294/job/1923 …
```
=> build: remove unneeded, failing labelling step

README.md
Apparently the only key having the `release_` prefix is the `created` key, the rest should all be present without that prefix.
I've updated the output keys in the readme, removing the `release_` prefix.
=> fix: update output key names

README.md
This PR updates the docs to switch usages to `target-branch` as this has changed in v4.
=> docs: update to `target-branch` option for non-default branch

src/index.ts
In 16.4.0, we correctly export CreateRelease and PullRequest which are types returned by Manifest.
=> cleanup: use built-in release-please types

src/index.ts
=> fix: log release-please version

action.yml, src/index.ts
This was originally part of [3.3.0](https://github.com/google-github-actions/release-please-action/blob/main/CHANGELOG.md#330-2022-08-10) (and fixed in [3.4.1](https://github.com/google-github-actions/release-please-action/blob/main/CHANGELOG.md#341-2022-08-24) to default to `github.server_url`). However, it was not part of 4.0.0.
Without this input, you have to provide both config and manifest files in order to set the `changelog-host` option. 
With this input, you can simply provide `release-type` and `changelog-host` without the need for config and manifest files. Also, since it defaults to `github.server_url`, most users will not even have to set it.
=> feat: add `changelog-host` input to `action.yml`

.github/workflows/release-please.yaml, README.md
- I'm not the maintainer, but I thought I put a pr for updating the old organization name to the new one
- related to: https://github.com/googleapis/release-please-action/issues/980
=> docs: updates references to old organization name

.github/workflows/release-please.yaml
build: use YOSHI_CODE_BOT_TOKEN
=> build: switch to code-suggester action

README.md
fix typo
searching the other codebase seems to confirm this is a typo (results show "local" not "loca")
https://github.com/search?q=repo%3Agoogleapis%2Frelease-please%20always-link-local&type=code
=> docs: fix small README typo

.github/workflows/release-please.yaml
There is a small issue in the step name for creating major/minor tags. Although it's not critical and doesn't impact any functionality, keeping a valid name in the step would be ideal.
Note: The documentation in `README.md` for creating major/minor tags is correct.
=> chore: update release tagging step name

CHANGELOG.md
These links were all broken. This should fix it.
=> chore(main): Update org name to `googleapis`

package.json
There are some references of the old repo (probably before it was moved to the `googleapis` org). 
This PR updates these references, but still keeps the author section as is.
=> chore: replace bcoe with googleapis references

README.md, action.yml, src/index.ts
Adds support and documentation for the skipLabeling option when running release-please from GitHub Actions.
This option in the config are ignored when running in release-please-action, and only honored when you pass it as an option via a command line. This PR adds the same support to GitHub action.
=> feat: support for skip-labeling parameter for GitHub action

README.md
These changes would have saved me some time. Maybe this will be true for other people as well.
=> docs: clarify organization settings required for permissions

README.md
`version` is included in the outputs, and it would be helpful to use instead of combine with major, minor, and patch.
See also:
https://github.com/google-github-actions/release-please-action/blob/cc61a07e2da466bebbc19b3a7dd01d6aecb20d1e/src/index.ts#L162-L193
https://github.com/googleapis/release-please/blob/72b0ab360c3d6635397e8b02f4d3f9f53932e23c/src/manifest.ts#L273-L280
=> doc: add version in outputs document

README.md
without the `issues: true` permission, users receive the following error:
Close #1105
=> docs: adds missing github action permissions to README

src/index.ts, test/release-please.ts
The `changelog-host` action parameter was being ignored when using manifest configuration files (`release-please-config.json`). This caused changelog links to always point to `github.com` instead of the specified GitHub Enterprise Server URL, breaking changelog functionality for GitHub Enterprise users.
The original implementation attempted to pass `changelogHost` through `manifestOverrides` to the `Manifest.fromManifest()` method. However, `changelogHost` is not part of the `ManifestOptions` interface - it belongs to the per-path `ReleaserConfig` interface. This architectural mismatch meant the parameter was silently ignored.
Modified the `loadOrBuildManifest()` function to:
1. Load the manifest normally without trying to pass `changelogHost` through manifest options
2. Post-process the …
=> fix: `changelog-host` parameter ignored when using manifest configuration

action.yml, src/index.ts, test/release-please.ts
Summary
This PR adds support for two new inputs to the release-please GitHub Action:
`versioning-strategy` Allows users to specify the versioning strategy to use for releases (e.g., default, always-bump-minor, etc.).
`release-as`: Allows users to specify the exact version to release as (e.g., 2.0.0).
Usage Example
```
- uses: googleapis/release-please-action@v4
with:
token: ${{ secrets.GITHUB_TOKEN }}
release-type: node
versioning-strategy: always-bump-minor
release-as: 2.0.0
```
Motivation
These options provide more flexibility and control over how versions are determined and released, addressing use cases where the default behavior is not sufficient.
=> feat: add ability to select versioning-strategy and release-as
