- .github/workflows/update-pr.yaml
- action.yml
- dist/index.js
- index.js
Allow release please to create releases.
> feat: handle creating releases

- dist/commit1.hbs
- dist/index.js
- package-lock.json
- package.json
Moves to https://github.com/googleapis/code-suggester for handling code suggestions.
> feat!: moves to code-suggester for managing code changes

- README.md
- dist/index.js
- package-lock.json
- package.json
Forking does not work in GitHub Actions, this pins to a version of release-please that does not try to fork.
> fix: do not try to fork

- README.md
- action.yml
- dist/index.js
- index.js
- package-lock.json
- package.json
syncs action with release-please@6.2.0, see:
https://github.com/googleapis/release-please/blob/master/CHANGELOG.md#620-2020-09-11
> feat(release-please): now supports large files; introduces fork option

- README.md
- package-lock.json
- package.json
>  feat(deps): release-please with support for alternate release branches

- package-lock.json
- package.json
Pulls in version of release-please with logic for sorting the listing of commits.
> fix(release-please): sort commits

- .github/workflows/release-please.yaml
- README.md
This updates the docs, but it's mostly an excuse to test the newest build of release-please.
> fix(docs): indicate correct version

- README.md
- action.yml
- index.js
- package-lock.json
- package.json
see: https://github.com/googleapis/release-please/blob/master/CHANGELOG.md#660-2020-10-28
> fix(ruby): properly support ruby release process

- README.md
- action.yml
- package-lock.json
- package.json
> feat(deps): upgrade to release-please 6.7.0

- README.md
- package-lock.json
- package.json
> feat(deps): upgrade to release-please 6.9.0

- .github/workflows/ci.yaml
- .gitignore
- index.js
- package-lock.json
- package.json
- test/release-please.js
> test: add tests and configure CI/CD

- README.md
- index.js
- package-lock.json
- package.json
See https://github.com/googleapis/release-please/pull/639
> feat(deps): latest version of release-please

- package-lock.json
- package.json
Release please had logic that was broken for merge commits when using a `path` to filter the commits.
> fix(release-please): fix for merge commits

- index.js
- package-lock.json
- test/release-please.js
output was being set when response was `undefined`.
> fix: do not set PR output, if no PR opened

- package-lock.json
- package.json
I believe this will address #164.
Refs #164
> fix(release-please): stop dynamically loading releasers

- package-lock.json
- package.json
Refs: https://github.com/googleapis/release-please/pull/673
> feat(release-please): fallback tag check is looser

- package-lock.json
- package.json
This pulls in @fasterthanlime's work adding support for a Rust releaser.
Fixes #163
> feat(release-please): add support for Rust

- package-lock.json
- package.json
Refs: https://github.com/googleapis/release-please/pull/669
> fix(release-please): fixes for monorepo path handling

- package-lock.json
- package.json
Fix bug caused by `package.json` being loaded late in process.
> fix(release-please): handle missing packageName release-pr

- package-lock.json
- package.json
Check more merged PRs when looking for a release PR.
> fix(release-please): increase page size for release PRs

- README.md
- package-lock.json
- package.json
Pulls in version of release-please with support for ocaml, thanks @phated 🎉 
Refs: https://github.com/googleapis/release-please/pull/697
> feat(release-please): add support for ocaml

- package-lock.json
- package.json
Release please that paginates by updated.
> fix(release-please): paginate PRs by updated

- package-lock.json
- package.json
fix(pagination): tagging can use 'updated' releases should use 'created'
> fix(release-please): fix whitespace issues in Rust

- package-lock.json
- package.json
Refs https://github.com/googleapis/release-please/blob/master/CHANGELOG.md#930-2021-01-22
> fix(release-please): uses alternate approach to find files in repo

- index.js
- package-lock.json
- package.json
- test/release-please.js
* uses factory from latest version
* use release-please@next
* fixes tests with factory usage
> fix(release-please): uses factory from latest version

- action.yml
- index.js
- test/release-please.js
1. add getBooleanInput function to get the correct boolean value of the input
2. add test for getBooleanInput function
3. add default value for the input
fix #215
>  fix: get the correct boolean value of the input

- README.md
> doc: added helm info

- action.yml
- index.js
release-please will attempt to detect pacakge-name from `package.json`.
> fix(config): packageName is optional

- package-lock.json
- package.json
- test/release-please.js
@targos this contains your fix, could you try `2.19.2` and see if it works for you (_once I merge this and the release PR._)
> fix(release-please): setup.py now retains formatting

- package-lock.json
- package.json
See: https://github.com/googleapis/release-please/blob/master/CHANGELOG.md#1100-2021-02-23
> feat(release-please): update to v11.0.0 of release please

- README.md
- action.yml
- index.js
- package-lock.json
- package.json
- test/release-please.js
Upgrade the release-please version to v11.1.0
Addition changes:
1. Fix the default `changelogSections` may occur type error.
2. Add `beforeEach` to overwrite the core functions.
3. Fix some document descriptions.
Close #258
> feat: add pull-request-title-pattern option

- package-lock.json
- package.json
Pull in release-please with manifest support.
> feat(release-please): update to release-please with manifest support

- package-lock.json
- package.json
See [CHANGELOG](https://github.com/googleapis/release-please/blob/master/CHANGELOG.md#1140-2021-03-24).
> feat(release-please): upgrade to release-please v11.4.0

- package-lock.json
- package.json
Includes fixes for lerna style releaser.
> fix(release-please): update to release-please@11.8.1

- package-lock.json
- package.json
Refs: https://github.com/googleapis/release-please/blob/master/CHANGELOG.md#features
> feat(release-please): update of release-please

- package-lock.json
- package.json
Refs: https://github.com/googleapis/release-please/blob/master/CHANGELOG.md#11110-2021-05-04
> feat(release-please): upgrade to release-please@11.11.0

- package-lock.json
- package.json
@fasterthanlime any other changes that you think we'll need other than using the latest release?
> feat(release-please): update to release-please with rust mono-repo support

- package-lock.json
- package.json
Latest release-please with fix for googleapis/release-please#988
> deps(release-please): release please with fix for pre-releases

- package-lock.json
- package.json
release please with updates for Python versioning.
> fix(relese-please): rollback bad release

- package-lock.json
- package.json
Update release-please version to [11.22.0](https://github.com/googleapis/release-please/releases/tag/v11.22.0)
> feat: add support for simple php projects

- action.yml
Hi everyone, 
I'm sorry that I forgot set config for action.yml on [PR #368](https://github.com/google-github-actions/release-please-action/pull/368).
I hope to help this project to be better, thanks.
> fix(input): miss inputs config for action.yml

- package-lock.json
- package.json
Pulls in latest release-please with various bug fixes.
> fix(release-please): pull in latest release-please

- README.md
> docs: update references to google-github-actions

- package-lock.json
- package.json
Updating release-please to get the new features available to the github action:
* ocaml: update opam project.opam.locked files
* add linked-versions plugin for grouping components
* introduce generic json updater
* introduce generic xml updater
> feat(deps): update release-please to 13.6.0

- README.md
fixes #438 
- update README.md
- fix the description of `pr` of the outputs table
- add `prs` to the outputs table
> docs: fix the description of the `outputs.pr`

- README.md
fixes #724
Added a section to mention required actions settings and workflow permissions.
> Provide information about workflow permissions

- README.md
also update the title of the 'adding additional files' to make it a bit clearer that this section is 'updating additional files' and further differentiate it from this new section.
> docs: guide on attaching files to github release

- package-lock.json
> fix(deps): bump dependency versions

- .github/workflows/ci.yaml
- action.yml
- package.json
Towards #852 
feat!: run on node20
> feat!: require node20 for the action code

- package-lock.json
- package.json
Blocked on https://github.com/googleapis/release-please/pull/2117
Towards #857
> deps!: upgrade release-please to v16

- .github/workflows/release-please.yaml
Update our own dogfood usage of the action
> build: update to use v4 configuration options

- README.md
- Replaced `v3` with `v4` in the examples
- Mapping names to certain references
- Changed `actions/checkout` version from `v2` to `v4`
- Changed `actions/setup-node` version from `v1` to `v4`
> docs: improved readme.md

- README.md
Added description how to access monorepo step result outputs using [] syntax
It took me several hours to figure out how to access the outputs of these monorepo packages. Hopefully, this will save others some time
> docs: add info how to access monorepo path outputs

- src/index.ts
The log is a bit misleading, I changed it to represent what it actually represents.
> fix: correct log output when creating releases

- test/release-please.ts
> chore: verify body contents when running tests
